using SyncApp.Helper;
using System.Text.Json.Serialization;

namespace SyncApp.Models.TopDesk;

public record OperatorFull(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("principalId")] string PrincipalId,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("accountType")] string AccountType,
    [property: JsonPropertyName("apiAccount")] bool? ApiAccount,
    [property: JsonPropertyName("surName")] string SurName,
    [property: JsonPropertyName("firstName")] string FirstName,
    [property: JsonPropertyName("dynamicName")] string DynamicName,
    [property: JsonPropertyName("initials")] string Initials,
    [property: JsonPropertyName("prefixes")] string Prefixes,
    [property: JsonPropertyName("birthName")] string BirthName,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("gender")] string Gender,
    [property: JsonPropertyName("language")] Language Language,
    [property: JsonPropertyName("branch")] Branch Branch,
    [property: JsonPropertyName("location")] Location Location,
    [property: JsonPropertyName("telephone")] string Telephone,
    [property: JsonPropertyName("mobileNumber")] string MobileNumber,
    [property: JsonPropertyName("faxNumber")] string FaxNumber,
    [property: JsonPropertyName("email")] string Email,
    [property: JsonPropertyName("exchangeAccount")] string ExchangeAccount,
    [property: JsonPropertyName("loginName")] string LoginName,
    [property: JsonPropertyName("loginPermission")] bool? LoginPermission,
    [property: JsonPropertyName("linkedPerson")] object LinkedPerson,
    [property: JsonPropertyName("jobTitle")] string JobTitle,
    [property: JsonPropertyName("department")] Department Department,
    [property: JsonPropertyName("budgetHolder")] BudgetHolder BudgetHolder,
    [property: JsonPropertyName("employeeNumber")] string EmployeeNumber,
    [property: JsonPropertyName("hourlyRate")] double? HourlyRate,
    [property: JsonPropertyName("networkLoginName")] string NetworkLoginName,
    [property: JsonPropertyName("mainframeLoginName")] string MainframeLoginName,
    [property: JsonPropertyName("hasAttention")] bool? HasAttention,
    [property: JsonPropertyName("attention")] object Attention,
    [property: JsonPropertyName("comments")] string Comments,
    [property: JsonPropertyName("installer")] bool? Installer,
    [property: JsonPropertyName("firstLineCallOperator")] bool? FirstLineCallOperator,
    [property: JsonPropertyName("secondLineCallOperator")] bool? SecondLineCallOperator,
    [property: JsonPropertyName("problemManager")] bool? ProblemManager,
    [property: JsonPropertyName("problemOperator")] bool? ProblemOperator,
    [property: JsonPropertyName("changeCoordinator")] bool? ChangeCoordinator,
    [property: JsonPropertyName("changeActivitiesOperator")] bool? ChangeActivitiesOperator,
    [property: JsonPropertyName("requestForChangeOperator")] bool? RequestForChangeOperator,
    [property: JsonPropertyName("extensiveChangeOperator")] bool? ExtensiveChangeOperator,
    [property: JsonPropertyName("simpleChangeOperator")] bool? SimpleChangeOperator,
    [property: JsonPropertyName("scenarioManager")] bool? ScenarioManager,
    [property: JsonPropertyName("planningActivityManager")] bool? PlanningActivityManager,
    [property: JsonPropertyName("projectCoordinator")] bool? ProjectCoordinator,
    [property: JsonPropertyName("projectActiviesOperator")] bool? ProjectActiviesOperator,
    [property: JsonPropertyName("stockManager")] bool? StockManager,
    [property: JsonPropertyName("reservationsOperator")] bool? ReservationsOperator,
    [property: JsonPropertyName("serviceOperator")] bool? ServiceOperator,
    [property: JsonPropertyName("externalHelpDeskParty")] bool? ExternalHelpDeskParty,
    [property: JsonPropertyName("contractManager")] bool? ContractManager,
    [property: JsonPropertyName("operationsOperator")] bool? OperationsOperator,
    [property: JsonPropertyName("operationsManager")] bool? OperationsManager,
    [property: JsonPropertyName("knowledgeBaseManager")] bool? KnowledgeBaseManager,
    [property: JsonPropertyName("accountManager")] bool? AccountManager,
    [property: JsonConverter(typeof(TopDeskDateTimeConverter))]
    [property: JsonPropertyName("creationDate")] DateTime? CreationDate,
    [property: JsonPropertyName("creator")] Creator Creator,
    [property: JsonConverter(typeof(TopDeskDateTimeConverter))]
    [property: JsonPropertyName("modificationDate")] DateTime? ModificationDate,
    [property: JsonPropertyName("modifier")] Modifier Modifier,
    [property: JsonPropertyName("hasApplicationPasswords")] bool? HasApplicationPasswords,
    [property: JsonPropertyName("optionalFields1")] OptionalFields OptionalFields1,
    [property: JsonPropertyName("optionalFields2")] OptionalFields OptionalFields2
);